
export const useErrorException = () => {
  return (
    <div>useErrorException</div>
  )
}
